server:
  port: 8085

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:mysql://localhost:3306/meditrack_auth?createDatabaseIfNotExist=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: meditrack_super_secret_key_2024_very_long_string
  expiration: 86400000